services:
  postgres:
    build: ./Database
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    build: ./Cache
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  qdrant:
    build: ./VectorDatabase
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    healthcheck:
      test: [ "CMD", "bash", "-c", "timeout 1 bash -c '</dev/tcp/localhost/6333'" ]
      interval: 10s
      timeout: 3s
      retries: 5

  recommendation-service:
    build: ./RecommendationService
    container_name: recommendation-service
    ports:
      - "8080:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QDRANT_URL: http://qdrant:6333
      FASTAPI_HOST: 0.0.0.0
      FASTAPI_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      qdrant:
        condition: service_healthy

  communication-service:
    build:
      context: .
      dockerfile: ./CommunicationService/Dockerfile
    container_name: communication-service
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RECOMMENDATION_SERVICE_URL: http://recommendation-service:8000
      FASTAPI_HOST: 0.0.0.0
      FASTAPI_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      recommendation-service: 
        condition: service_started

volumes:
  postgres-data:
  qdrant-data:
