[tool.mypy]
strict = false
python_version = "3.13"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:asyncio",
    "ignore::DeprecationWarning:starlette",
    "ignore::DeprecationWarning:fastapi",
]
